version: '3.4'

services:
  rest:
    image: ${DOCKER_REGISTRY-}rest
    build:
      context: .
      dockerfile: rest/Dockerfile
    networks:
      - my-network

  php:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "8080:80"  # Map port 8081 on the host to port 80 in the PHP container
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
