version: '3.4'

services:
  rest:
    image: ${DOCKER_REGISTRY-}rest
    build:
      context: .
      dockerfile: rest/Dockerfile
    ports:
      - "8081:443"
    networks:
      - my-network

  php:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "8080:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
